### ISSUE TITLE
urdf file format

### ISSUE THREAD

**Issue by linuxsocke** [Intelligent-Quads/iq_sim#4]
Hello,

I tried to spawn models with the urdf format but it is kind of unstable when having an imu sensor mounted. 

Often it says:

`gyro[0] did not converge: diff=-57.29578 dps (expected < 0.100000)`

But sometimes it calibrates and then it takes off and flys quite good.

When adding a gps sensor it will always calibrate. But then I got errors with PreArm: Need 3D Fix and when taking off it starts flying around the position like crazy.  

Any suggestions whats happening? I also can show code. I tried to follow the rotors_simulator and px4 examples.

**Comment by linuxsocke** [comment]
Ok, now the calibration always works when using an imu with update rate 100 unlike to the .sdf file example where it is 1000. Dont ask me why.. So far it works kind of with urdf.

**Comment by MingiJeong** [comment]
Hi! would you mind sharing .urdf file example which works with Ardupilot?

**Comment by arjungupta72** [comment]
@linuxsocke  could you please share the .urdf file for the drone which works with ardupilot. @MingiJeong  did you ever get the urdf file from here or elsewhere somehow? If so please share it.
